In [12]:
# import numpy
import numpy as np
# create array x
x = np.array([[0,11,222,3333,44444],[6,77,888,9999,3232323]])

In [13]:
# print the shape of x
x.shape

(2, 5)

In [15]:
# create a two dimensional array
y = np.array([[1,2],[3,4]])

(2, 2)

In [16]:
# print shape of 2d array
print y.shape

(2, 2)


In [42]:
#Independent Practice: Topic (20 minutes)
#Create 2 arrays. Add them together, subtract them, and do the dot product.
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

print np.add(a,b)
print np.subtract(a,b)
print np.dot(a,b)

[5 7 9]
[-3 -3 -3]
32


In [44]:
#Create a 3 dimensional array
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print np.array([a,b,c])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Create a 5 dimensional array

In [46]:
#5 dimensional array
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
d = np.array([10,11,12])
e = np.array([13,14,5])
print np.array([a,b,c,d,e])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14  5]]


In [19]:
# reshape the array to 2 x 6
y = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
y.shape

(2, 6)

In [6]:
# reshape the array to 1 x 12

In [7]:
# transpose the array

In [8]:
# indexing method 1

In [9]:
# indexing method 2

In [13]:
# indexing method 3

In [12]:
# indexing method 4

In [11]:
# indexing method 5

In [10]:
# indexing method 6