In [2]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
print a
print b

[1 2 3 4 5]
[5 4 3 2 1]


In [48]:
#1x vector
c = np.array([1,2,3,4,5,6])
print c

[1 2 3 4 5 6]


In [44]:
print np.matrix(a[0:2]), np.matrix(a[0:2])
#print np.matrix(b)

 [[1 2]] [[1 2]]


In [57]:
#2x2 matrix
print np.array([a[0:2],b[3:5]])

[[1 2]
 [2 1]]


In [63]:
#3x3 matrix
print np.array([a[0:3],b[0:3],a[0:3]])

[[1 2 3]
 [5 4 3]
 [1 2 3]]


In [64]:
#4x8 array
a = np.array([[0,1,2,3,4,5,6,7],[0,1,2,3,4,5,6,7],[0,1,2,3,4,5,6,7],[0,1,2,3,4,5,6,7]])

In [66]:
a

array([[0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7]])

In [67]:
a.shape

(4, 8)

In [82]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
print a 
print b
print [a[0]+b[2], a[2]+b[3]]
np.add(a,b)


[1 2 3 4 5]
[5 4 3 2 1]
[4, 5]


array([6, 6, 6, 6, 6])

In [80]:
a = [1,2,3]
b = [3,2,1]

In [81]:
np.add(a,b)

array([4, 4, 4])

In [83]:
#set 1
a = [1, 2, 3, 4, 5, 6]
b = [-6, -5, -4, -3, -2, -1]
np.add(a,b)

array([-5, -3, -1,  1,  3,  5])

In [97]:
#set 2
a = [-1, -2, -3, -4, -5, -6]
b = [-6, -5, -4, -3, -2, -1]
np.subtract(a,b)

array([ 5,  3,  1, -1, -3, -5])

In [102]:
#set 3
a = [101, 201, 33.22, -423, 5.3234, -6.234]
b = [-601, 501.33, -113, 3.3000003, -2, -1.999999999999999]
np.subtract(a,b)
#print c

array([ 702.       , -300.33     ,  146.22     , -426.3000003,
          7.3234   ,   -4.234    ])

In [106]:
#set 4
a = [-101, -201, -33.22, 423, -5.3234, -34]
b = [601, -501.33, 113, -3.3000003, 'l', 10.999999999999999]

for index,value in enumerate(b):
    print index,value
    if type(value) == str:
        print "found str"
        b[index] = 0
b
np.subtract(a,b)

0 601
1 -501.33
2 113
3 -3.3000003
4 l
found str
5 11.0


array([-702.       ,  300.33     , -146.22     ,  426.3000003,
         -5.3234   ,  -45.       ])

In [12]:
#Independent Practice: Topic (20 minutes)
#Create 2 arrays. Add them together, subtract them, and do the dot product.
#Bonus:

#Create a 3 dimensional array
#Create a 5 dimensional array

In [8]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

print np.add(a,b)
print np.subtract(a,b)
print np.dot(a,b)

[5 7 9]
[-3 -3 -3]
32
